---

apps_dir: /var/data/apps

app_name: metrics
app_root: '{{ apps_dir }}/{{ app_name }}'
app_runtime_dir: '{{ app_root }}/runtime'
app_ssl_dir: '{{ app_root }}/ssl'
app_volumes_dir: '{{ app_root }}/volumes'
app_domain: localhost

app_gafana_version: 8.4.6
grafana_port: 3000

app_telegraf_version: 1.20.4

influxdb_database: telegraf
influxdb_retention_duration: 4w
app_influxdb_expose_port: 8086
app_influxdb_version: 1.8.10

# Grafana Github Authenticaion is not tested.
gf_auth_github_enabled: false
gf_auth_github_client_id: ''
gf_auth_github_client_secret: ''
gf_auth_github_team_ids: ''
gf_auth_github_allowed_organizations: ''

# It is recomended to pass the next vars as extra variables to be secure.
grafana_admin_password: secret
influxdb_admin_user: secret
influxdb_admin_password: secret
