---

apps_dir: /var/data/apps

app_name: metrics
app_root: '{{ apps_dir }}/{{ app_name }}'
app_runtime_dir: '{{ app_root }}/runtime'
app_ssl_dir: '{{ app_root }}/ssl'
app_volumes_dir: '{{ app_root }}/volumes'
app_domain: localhost

app_gafana_version: 8.4.0
grafana_admin_password: terminator
grafana_port: 3000

influxdb_admin_user: schwarzenegger
influxdb_admin_password: arnold
influxdb_database: telegraf
influxdb_retention_duration: 4w
app_influxdb_expose_port: 8086

gf_auth_github_enabled: false
gf_auth_github_client_id: ''
gf_auth_github_client_secret: ''
gf_auth_github_team_ids: ''
gf_auth_github_allowed_organizations: ''
