---

- name: Update apt cache if needed.
  become: true
  apt:
    update_cache: true
    cache_valid_time: 86400

- name: Ensure basic dependencies are installed.
  become: true
  apt:
    name:
      - curl
      - docker.io
      - docker-compose
    state: present
