apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    typeLogoUrl: public/app/plugins/datasource/influxdb/img/influxdb_logo.svg
    access: proxy
    database: {{ influxdb_database }}
    user: ""
    url: https://{{ instance }}-influxdb:8086
    basicAuth: true
    isDefault: true
    editable: false
    jsonData:
      tlsSkipVerify: true
      httpMode: POST
    secureJsonData:
      basicAuthUser: {{ influxdb_admin_user }}
      basicAuthPassword: {{ influxdb_admin_password }}
      password: ""
