---

apps_dir: /var/data/apps

app_name: metrics.demo.jet.dev
app_domain: metrics.demo.jet.dev
app_ssl_dir: /var/data/ssl/{{ app_domain }}
app_influxdb_expose_port: 8443

grafana_admin_password: admin

influxdb_admin_user: influx
influxdb_admin_password: influx
influxdb_database: telegraf
influxdb_retention_duration: 2w
